add missed data type
MasoniteFramework/orm pull request #321
Opened 2021-01-21 15:51 UTC by erhuabushuo

2021-01-22 05:10 UTC, josephmancuso requested changes
Everything looks good. Does any changes to the MYSQL grammar need to be done?

2021-01-23 11:09 UTC, erhuabushuo commented
@josephmancuso MySQL grammar doesn't need to be change,  other platform integer types do not support length, so they need to put in types_without_lengths.

2021-01-23 14:26 UTC, josephmancuso approved these changes

2021-01-23 14:26 UTC, merged

2021-01-23 14:26 UTC, josephmancuso commented
This is all great! Thanks!