Fix for scopes/UUIDPrimaryKeyScope.py always replacing primary_key
MasoniteFramework/orm pull request #486
Opened 2021-08-06 21:31 UTC by garzola

Fix for scopes/UUIDPrimaryKeyScope.py always replacing the primary_key.  It should only provide a primary_key when one has not been provided.

2021-08-06 21:33 UTC, garzola commented
This is for Issue #486

2021-08-09 16:58 UTC, josephmancuso requested changes

2021-08-09 16:58 UTC, josephmancuso commented on src/masoniteorm/scopes/UUIDPrimaryKeyScope.py
> +        if not builder._model.__primary_key__:
This conditional is checking the model has a primary key. That is wrong. This should be replaced with:

```suggestion
        if builder._model.__primary_key__ not in builder._creates:
```

2021-08-09 16:58 UTC, josephmancuso commented on src/masoniteorm/scopes/UUIDPrimaryKeyScope.py
> +        if not builder._model.__primary_key__:
Thats why the tests are failing

2021-08-10 06:57 UTC, garzola commented
After looking carefully at this, I have a much better understanding of what
was happening.  Thanks for the comment.  I have updated the pull request
with this change.

I appreciate you taking the time to explain what was really needed.

Thanks,

Gustavo

--
"We must be willing to let go of the life we've planned, so as to have the
 life that is waiting for us."
                                   - Joseph Campbell


On Mon, Aug 9, 2021 at 9:59 AM Joseph Mancuso ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In src/masoniteorm/scopes/UUIDPrimaryKeyScope.py
> <https://github.com/MasoniteFramework/orm/pull/486#discussion_r685366266>:
>
> > @@ -23,7 +23,9 @@ def generate_uuid(self, builder, uuid_version):
>          return str(uuid_func(*args))
>
>      def set_uuid_create(self, builder):
> -        uuid_version = getattr(builder._model, "__uuid_version__", 4)
> -        builder._creates.update(
> -            {builder._model.__primary_key__: self.generate_uuid(builder, uuid_version)}
> -        )
> +        # if there is already a primary key, no need to set a new one
> +        if not builder._model.__primary_key__:
>
> Thats why the tests are failing
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/MasoniteFramework/orm/pull/486#discussion_r685366266>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAHRF7D52YJGYE6QQ2V74GLT4ACNZANCNFSM5BWUNOHQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&utm_campaign=notification-email>
> .
>

2021-08-10 22:09 UTC, josephmancuso commented
Pushed a small test fix to this branch

2021-08-10 22:46 UTC, josephmancuso approved these changes
Looks good to me!

2021-08-10 22:46 UTC, merged