Added .first_or() method to Model
MasoniteFramework/orm pull request #647
Opened 2022-04-25 00:26 UTC by JarriqTheTechie

Retrieves first record matching a given criteria. If no record exists matching the given criteria, a user-defined callback function will be executed.

Example usage.

```
def send_mail():
    return "mail sent"
```

`User.first_or({"name": "bob"}, lambda: send_mail())`
If no user with the name bob is found then callback function `send_mail()` will be executed.

2022-04-25 00:27 UTC, JarriqTheTechie commented
@josephmancuso ready for review.

2022-05-02 01:53 UTC, josephmancuso requested changes

2022-05-02 01:53 UTC, josephmancuso commented on src/masoniteorm/models/Model.py
> +        self._check_is_callable(callback)
what is this doing? You built a check for is callable but not using the return value form it anywhere

2022-05-15 19:04 UTC, josephmancuso commented on src/masoniteorm/models/Model.py
> +        self._check_is_callable(callback)
@JarriqTheTechie any update on this? This is wrong right?

2022-06-10 03:35 UTC, josephmancuso commented
@JarriqTheTechie any update on these comments? I'd like to get this PR merged

2022-06-24 01:53 UTC, closed without merging