Added exists and doesnt_exist method to QueryBuilder.
MasoniteFramework/orm pull request #694
Opened 2022-05-27 10:07 UTC by JarriqTheTechie

Check for the existence of rows matching your query criteria. Useful alternative to performing a row count.

2022-05-27 10:12 UTC, JarriqTheTechie commented
@josephmancuso ready for review.

2022-05-28 14:06 UTC, Marlysson commented
Closes #687

2022-06-05 21:01 UTC, josephmancuso requested changes

2022-06-05 21:01 UTC, josephmancuso commented on src/masoniteorm/models/Model.py
> +        "doesnt_exists",
This method should be `doesnt_exist` i think and not `doesnt_exists`. the plural on the doesnt_exists doesn't really make gramatically sense.

2022-06-05 21:01 UTC, josephmancuso commented on src/masoniteorm/models/Model.py
> +        "doesnt_exists",
Nevermind this is just a typo here

2022-06-05 21:03 UTC, josephmancuso approved these changes

2022-06-05 21:08 UTC, merged