added delete_quietly method on Model
MasoniteFramework/orm pull request #809
Opened 2022-10-13 11:47 UTC by JarriqTheTechie

This method calls the delete method on a model without firing the delete & deleting observer events.
Instead of calling:

User().delete(...)

you can use this:

User.delete_quietly(...)

2022-10-13 11:49 UTC, JarriqTheTechie commented
@girardinsamuel / @josephmancuso please review.

2022-10-13 13:55 UTC, Marlysson commented
Shouldn't activate again the events after this operation as save and updte quietly does with `.with_events()` method?

2022-10-14 00:04 UTC, josephmancuso requested changes
@Marlysson is right here. You need to set `with_events()` again.

2022-10-14 00:08 UTC, josephmancuso approved these changes
Changed a few things. Your change would have deleted the whole table

2022-10-14 00:12 UTC, merged

2022-10-14 00:13 UTC, JarriqTheTechie commented
Thanks @Marlysson @josephmancuso