added update_quietly method on Model
MasoniteFramework/orm pull request #811
Opened 2022-10-13 12:06 UTC by JarriqTheTechie

This method calls the update method on a model without firing the updated & updating observer events. Updated/Updating are toggled back on once update_quietly has been ran.

Instead of calling:

User().update(...)

you can use this:

User.update_quietly(...)

2022-10-13 12:06 UTC, JarriqTheTechie commented
@josephmancuso / @girardinsamuel please review.

2022-10-14 00:50 UTC, josephmancuso requested changes
This should be `update_quietly` and do the same changes i did in the other PR's

2022-10-25 01:05 UTC, closed without merging

2022-10-25 01:11 UTC, JarriqTheTechie commented
Hi @josephmancuso, I'll make the changes this weekend. Been having a boxing match with COVID.

2022-10-25 01:12 UTC, josephmancuso commented
of course no worries just doing some cleaning up