fix: Belongs to many - Table can't be without an underscore
MasoniteFramework/orm pull request #825
Opened 2022-10-27 09:56 UTC by maicol07

Fixes #803

2022-10-28 00:44 UTC, josephmancuso requested changes
This won't work in the scenario that someone only specifies the first key right? like if someone specifies the self.local_key but not the self.foreign_key.

In that case i think it would overwrite whatever they specified as the self.local_key

2022-10-28 13:12 UTC, maicol07 commented
> This won't work in the scenario that someone only specifies the first key right? like if someone specifies the self.local_key but not the self.foreign_key.
> 
> In that case i think it would overwrite whatever they specified as the self.local_key

Why? Inside the elie there's the or that should keep the key id it's defined

2022-11-07 09:06 UTC, maicol07 commented
@josephmancuso ↑

2022-11-07 23:24 UTC, josephmancuso approved these changes

2022-11-07 23:24 UTC, merged