Feature/find_or
MasoniteFramework/orm pull request #837
Opened 2023-02-01 16:44 UTC by JarriqTheTechie

Retrieves record by primary key. If no record exists matching the given criteria, a user-defined callback function will be executed.

eg.

id: int = 1024
callback: Callable = lambda a, b : a * b
arguments: tuple = (5, 6)

User.find_or(id, callback, arguments)

The callback will run only if user with id 1024 is not found. Arguments to the callback are passed in as tuples.

2023-02-01 16:45 UTC, JarriqTheTechie commented
@josephmancuso please review.

2023-09-30 19:15 UTC, josephmancuso requested changes
needs a test

2023-12-06 02:28 UTC, JarriqTheTechie commented
Test has now been added. @josephmancuso please review.

2023-12-06 03:03 UTC, josephmancuso approved these changes
code review looks good

2023-12-06 03:03 UTC, merged