Add some type-hints to Model.py
MasoniteFramework/orm pull request #881
Opened 2024-04-05 03:36 UTC by JarriqTheTechie

2024-04-05 11:42 UTC, JarriqTheTechie commented
When adding multiple return types I will use Union instead of pipe operator.

2024-04-05 13:59 UTC, josephmancuso requested changes

2024-04-05 13:59 UTC, josephmancuso commented on src/masoniteorm/models/Model.py
> +    __internal_cast_map__: list[str, Any] = {
is this a list or is it a dict?

2024-04-05 14:00 UTC, josephmancuso commented
also tests are failing

2024-04-05 14:14 UTC, JarriqTheTechie commented
> also tests are failing

Tests are failing due to issues with backwards compatibility with older versions of python. That's why I'll use Union types instead of | as a type separator.

2024-06-03 12:46 UTC, josephmancuso commented
please fix tests failing. i'd like to merge this in

2024-06-09 13:50 UTC, josephmancuso commented
closing bc of tests failing

2024-06-09 13:50 UTC, closed without merging