fix: values in compile_alter_sql
MasoniteFramework/orm pull request #885
Opened 2024-06-19 20:39 UTC by Kyrela

fix #884

2024-06-19 20:47 UTC, josephmancuso requested changes
just needs a test

2024-06-19 20:49 UTC, Kyrela commented
Should I edit `BaseConnection.py` to remove the additional blank line?

2024-06-19 20:57 UTC, josephmancuso commented
> Should I edit `BaseConnection.py` to remove the additional blank line?

idk what youre talking about but sure i think

2024-06-19 21:00 UTC, Kyrela commented
I'm talking about the lint results.
![image](https://github.com/MasoniteFramework/orm/assets/44508673/5b1fb561-db6f-42be-b102-f976deea6297)
No link with my PR, but as the linter is triggered by it, I guess I could fix it?

2024-06-19 21:01 UTC, josephmancuso commented
oh, yes please

2024-06-19 21:01 UTC, josephmancuso commented
adding tests are pretty simple if you could add one for enum

2024-06-19 21:02 UTC, Kyrela commented
Done

2024-06-19 21:03 UTC, Kyrela commented
> adding tests are pretty simple if you could add one for enum

Oh, sure, was thinking about it.

2024-06-19 21:20 UTC, Kyrela commented
Not sure about the quality of my tests tbh, but I added a test for the bug referenced in issue #885 and tests for changing an enum or adding it in a new table. If these are good, should I add them for the other sql dialects?

2024-06-19 22:20 UTC, josephmancuso commented
> Not sure about the quality of my tests tbh, but I added a test for the bug referenced in issue #885 and tests for changing an enum or adding it in a new table. If these are good, should I add similar ones for the other sql dialects?

yes please, code looks good 👍

2024-07-07 20:45 UTC, Kyrela commented
Hello, any update?

2024-07-30 13:26 UTC, josephmancuso approved these changes

2024-07-30 13:29 UTC, josephmancuso approved these changes

2024-07-30 13:29 UTC, merged